//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTap2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thietbi
    {
        public Nullable<int> Madv { get; set; }
        public Nullable<int> Maloai { get; set; }
        public int Matb { get; set; }
        public string Tentb { get; set; }
        public string Nuocsx { get; set; }
        public Nullable<int> Namsx { get; set; }
        public string Ngaysd { get; set; }
        public string Ghichu { get; set; }
    
        public virtual Donvi Donvi { get; set; }
        public virtual Loaithietbi Loaithietbi { get; set; }
    }
}
